### ISSUE TITLE
Ask for advice of FFI code

### ISSUE THREAD

**Issue by huangyt** [sansuido/sdl2#2]
HI, sdl2 is a amazing work, thank for you share.
  I'm a beginner of dart, and coding by ffi.
  And I have a question: code in "\lib\sdl2\generated\lib_*.dart", had a coment in first line: "THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY."

  My question is: all ffi code is your finished by coding or there generated by a tool? command or sth?

  Thank you, ^_^, if has some "magic " can auto makes "*.h" to "*.dart", pls tell me. the FFI is killing me .

**Comment by huangyt** [comment]
FFIGEN?

**Comment by sansuido** [comment]
Hello, huangyt.
Thank you for using SDL2 for dart.

The "generated folder" is created by automatic generation.
As you can see, it scans all header files and creates all dart files.
The text "THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY." Refers to the source of win32 for dart.

There is a unique private environment that does not use "ffigen".
I'm sorry, it's a very dirty source, so I keep it private.
