### ISSUE TITLE
无法在flutter手机设备上运行吗

### ISSUE THREAD

**Issue by peter100u** [sansuido/sdl2#3]
我想在手机上运行效果，请问怎么做呢

**Comment by sansuido** [comment]
Hello, peter100u.
Since this package uses ffi, it is difficult to upload a dynamic library in order to operate it with flutter.
If you are thinking of using flutter, flame is recommended.
https://pub.dev/packages/flame

**Comment by peter100u** [comment]
> 

非常感谢
