### ISSUE TITLE
libSDL2_gfx.so: cannot open shared object file

### ISSUE THREAD

**Issue by jakeklassen** [sansuido/sdl2#4]
When trying `dart run example/fps_manager.dart` I get the following error:

```sh
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'libSDL2_gfx.so': libSDL2_gfx.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      dylibOpen (package:sdl2/sdl2/dylib.dart:25:25)
#3      libSdl2Gfx (package:sdl2/sdl2/generated/lib_sdl_gfx.dart:8:26)
#4      libSdl2Gfx (package:sdl2/sdl2/generated/lib_sdl_gfx.dart)
#5      sdlInitFramerate (package:sdl2/sdl2/generated/lib_sdl_gfx.dart:15:42)
#6      FpsManageerPointerEx.init (package:sdl2/sdl2/ex/gfx/fps_manager.dart:9:5)
#7      main (file:///home/jake/workspace/source/dart-sdl2/example/fps_manager.dart:34:7)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**My Environment**

OS: Windows 11 - WSL2 Ubuntu 22.04
Dart: Dart SDK version: 2.18.6 (stable) (Unknown timestamp) on "linux_x64"

**Comment by sansuido** [comment]
Hello, jakeklassen.
sdl2-gfx is not an official library, so it needs to be installed separately.

sudo apt-get install -y libsdl2-gfx-dev

![image](https://user-images.githubusercontent.com/13101762/208271933-84672d2d-2b98-40e9-8046-63a899653c2f.png)

**Comment by sansuido** [comment]
Hello, jakeklassen.
sdl2-gfx is not an official library, so it needs to be installed separately.

sudo apt-get install -y libsdl2-gfx-dev

**Comment by jakeklassen** [comment]
@sansuido ah right, thanks that worked perfectly.
